#!/bin/bash
# bash completion support for validation.
#
# The contained completion routines provide support for completing
# dva subsections, commands and options.

_dva_tab() {

  local dva_cur dva_prev dva_options dva_sections grep_dva_sections optional_svalidate_args optional_result_args

  COMPREPLY=()
  dva_cur=${COMP_WORDS[COMP_CWORD]}
  dva_prev=${COMP_WORDS[COMP_CWORD-1]}
  dva_options="-h --help -l --loglevel -c --conf"
  dva_sections="svalidate validate result summary bugzilla"
  grep_dva_sections=$(echo $COMP_LINE | egrep -o "(svalidate|validate|result|summary|bugzilla)" )
  optional_svalidate_args="-h --help -i --istream -o --ostream -t --test-whitelist \
                           -T --test-blacklist -s --stage-whitelist -S --stage-blacklist \
                           -g --tags-whitelist -G --tags-blacklist -n --no-action"
  optional_result_args="-h --help -i --istream -o --ostream -V --verbose"

  if [[ $COMP_LINE == *\ -h?* ]] \
    || [[ $COMP_LINE == *--help?* ]]; then
      return
  fi

  if [[ ${dva_prev} == -l ]] || [[ ${dva_prev} == --loglevel ]]; then
        COMPREPLY=( $( compgen -W "DEBUG ERROR INFO WARNING debug error info warning" -- "$dva_cur" ) )
        return
  fi

  if [[ -z "${grep_dva_sections}" ]]; then
    COMPREPLY=( $( compgen -W "$dva_options $dva_sections" -- "$dva_cur" ) )
    return
  fi

  #$COMP_LINE 2>&1 | egrep -q "^dva: error:" && return
  case "$grep_dva_sections" in
    svalidate)
      COMPREPLY=( $( compgen -W "$optional_svalidate_args" -- $dva_cur ) );;
    validate)
      COMPREPLY=( $( compgen -W "$optional_svalidate_args --parallel-instances --parallel-tests \
                                                          --sorted-mode --test-modules" -- $dva_cur ) );;
    result)
      COMPREPLY=( $( compgen -W "$optional_result_args" -- $dva_cur ) );;
    summary)
      COMPREPLY=( $( compgen -W "-h --help -i --istream -c --compare -t --test-whitelist \
                                 -m --html" -- $dva_cur ) );;
    bugzilla)
      COMPREPLY=( $( compgen -W "$optional_result_args -u --user -p --password -U --url \
                                                       -d --debug-mode -C --component -R --product \
                                                       -P --pool-size" -- $dva_cur ) );;
  esac
}

complete -F _dva_tab dva

