#!/usr/bin/env python
import sys
import logging
import argparse
import aaargh
import re

from dva.tools import catching
# load all testing modules
from dva.test import *

RE_ANY = re.compile('.*')

LOG = None
APP = aaargh.App(description="dva's validation. again.")

class LogAction(argparse.Action):
    '''custom logging action'''
    def __call__(self, parser, namespace, value, option_string=None):
        '''loglevel setting action'''
        if not hasattr(logging, value.upper()):
            # no such level
            raise argparse.ArgumentError('invalid loglevel name: %s' % value)
        logging.basicConfig(level=getattr(logging, value.upper()))
        global LOG
        LOG = logging.getLogger(__name__)
        setattr(namespace, self.dest, value.upper())

APP.arg('-l', '--loglevel', help='set log level', action=LogAction, default='WARNING',
        choices=['DEBUG', 'ERROR', 'INFO', 'WARNING', 'debug', 'error', 'info', 'warning']) 
APP.arg('-c', '--conf', help='use conf file', default=None)


@APP.cmd(help='validate in series')
@APP.cmd_arg('-i', '--istream', help='input filename', type=argparse.FileType('r'), default=sys.stdin)
@APP.cmd_arg('-o', '--ostream', help='output filename', type=argparse.FileType('w'), default=sys.stdout)
@APP.cmd_arg('-t', '--test-whitelist', help='regexp testname list', default=['.*'], nargs='+', metavar='PATTERN')
@APP.cmd_arg('-T', '--test-blacklist', help='regexp testname list', default=[], nargs='+', metavar='PATTERN')
@APP.cmd_arg('-s', '--stage-whitelist', help='regexp stagename list', default=['.*'], nargs='+', metavar='PATTERN')
@APP.cmd_arg('-S', '--stage-blacklist', help='regexp stagename list', default=[], nargs='+', metavar='PATTERN')
@APP.cmd_arg('-n', '--no-action', help='take no action', action='store_true')
def svalidate(loglevel, conf, istream, ostream, test_whitelist, test_blacklist, stage_whitelist, stage_blacklist, no_action):
    logging.basicConfig(level=getattr(logging, loglevel))
    from dva.work.serial_main import main as main
    main(conf, istream, ostream, test_whitelist, test_blacklist, stage_whitelist, stage_blacklist, no_action)

@APP.cmd(help='validate in parallel')
@APP.cmd_arg('-i', '--istream', help='input filename', type=argparse.FileType('r'), default=sys.stdin)
@APP.cmd_arg('-o', '--ostream', help='output filename', type=argparse.FileType('a'), default=sys.stdout)
@APP.cmd_arg('-t', '--test-whitelist', help='regexp testname list', default=['.*'], nargs='+', metavar='PATTERN')
@APP.cmd_arg('-T', '--test-blacklist', help='regexp testname list', default=[], nargs='+', metavar='PATTERN')
@APP.cmd_arg('-s', '--stage-whitelist', help='regexp stagename list', default=['.*'], nargs='+', metavar='PATTERN')
@APP.cmd_arg('-S', '--stage-blacklist', help='regexp stagename list', default=[], nargs='+', metavar='PATTERN')
@APP.cmd_arg('-n', '--no-action', help='take no action', action='store_true')
def validate(loglevel, conf, istream, ostream, test_whitelist, test_blacklist, stage_whitelist, stage_blacklist, no_action):
    logging.basicConfig(level=getattr(logging, loglevel))
    from dva.work.data_parallel_main import main
    main(conf, istream, ostream, test_whitelist, test_blacklist, stage_whitelist, stage_blacklist, no_action)



sys.exit(APP.run())
